# Generated by Django 6.1.1 on 2026-10-06 10:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Маршрут"
                    ),
                ),
            ],
            options={
                "verbose_name": "маршрут",
                "verbose_name_plural": "маршруты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
            ],
            options={
                "verbose_name": "станция",
                "verbose_name_plural": "станции",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="ФИО")),
                (
                    "passport",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Паспорт"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passenger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "пассажир",
                "verbose_name_plural": "пассажиры",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядок")),
                (
                    "minutes_from_start",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Минут от отправления"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="railway.route",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="railway.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "остановка",
                "verbose_name_plural": "остановки",
                "ordering": ["route", "order"],
            },
        ),
        migrations.AddField(
            model_name="route",
            name="stations",
            field=models.ManyToManyField(
                related_name="routes",
                through="railway.RouteStop",
                to="railway.station",
                verbose_name="Станции",
            ),
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, unique=True, verbose_name="Номер"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "train_type",
                    models.CharField(
                        choices=[
                            ("fast", "Скорый"),
                            ("passenger", "Пассажирский"),
                            ("high_speed", "Высокоскоростной"),
                        ],
                        default="fast",
                        max_length=12,
                        verbose_name="Тип",
                    ),
                ),
                ("departure", models.DateTimeField(verbose_name="Отправление")),
                (
                    "seats_total",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Мест",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "По расписанию"),
                            ("delayed", "Задерживается"),
                            ("departed", "Отправлен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="scheduled",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trains",
                        to="railway.route",
                        verbose_name="Маршрут",
                    ),
                ),
            ],
            options={
                "verbose_name": "поезд",
                "verbose_name_plural": "поезда",
                "ordering": ["departure"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Место",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Цена"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Оплачен"), ("returned", "Возвращён")],
                        default="paid",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Куплен"),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="railway.passenger",
                        verbose_name="Пассажир",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="railway.train",
                        verbose_name="Поезд",
                    ),
                ),
            ],
            options={
                "verbose_name": "билет",
                "verbose_name_plural": "билеты",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="routestop",
            constraint=models.UniqueConstraint(
                fields=("route", "order"), name="unique_stop_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "paid")),
                fields=("train", "seat"),
                name="unique_active_seat",
            ),
        ),
    ]
