from typing import Protocol

from models.entities import Ticket


class TicketRepository(Protocol):
    def add(self, ticket: Ticket) -> None: ...
    def get(self, ticket_id: int) -> Ticket | None: ...
    def get_all(self) -> list[Ticket]: ...
    def update(self, ticket: Ticket) -> None: ...
    def delete(self, ticket_id: int) -> None: ...
    def next_id(self) -> int: ...
